config/routes.rb
Rails.application.routes.draw do
  root 'groups#index'
  devise_for :users
  resources :users, only: %i(index)
  resources :friends, only: %i(index create) do
    collection do
      get :search
    end
  end
  resources :groups, only: %i(index show create) do
    resources :messages, only: %i(create)
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  belongs_to :friend, class_name: 'User', foreign_key: :friend_id
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    current_user_and_friends_ids = [current_user.id]
    users_friends = Friend.where(user_id: current_user.id)
    users_friends.each do |friend|
      current_user_and_friends_ids << friend.friend_id
    end
    @friends = User.where(id: current_user_and_friends_ids).where.not(id: current_user.id).includes(:user_groups).includes(:groups)
  end

  def search
    current_user_and_friends_ids = [current_user.id]
    users_friends = Friend.where(user_id: current_user.id)
    users_friends.each do |friend|
      current_user_and_friends_ids << friend.friend_id
    end
    @not_friends = User.where.not(id: current_user_and_friends_ids)
  end

  def create
    new_friend1 = Friend.new(user_id: current_user.id, friend_id: friends_params[:friend_id])
    new_friend2 = Friend.new(user_id: friends_params[:friend_id], friend_id: current_user.id )
    if new_friend1.save && new_friend2.save
      redirect_to friends_url
    end
  end

  private

  def friends_params
    params.require(:friend).permit(:friend_id)
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.haml
.group_index_header
  = current_user.name
  = link_to '友人検索', search_friends_path
  = link_to 'トーク一覧', groups_path
  = link_to "ログアウト", destroy_user_session_path, method: :delete
- if @friends.present?
  - @friends.each do |friend|
    .friends_index
      .friend_image
        = friend.name + "のアイコン"
      .friend_name
        = friend.name
      .start_talk
        - if (friend.groups & current_user.groups).present?
          - group = (friend.groups & current_user.groups)[0]
          = link_to 'トークに戻る', group_path(group)
        - else
          = form_with model: @new_group, url: "/groups" do |f|
            = f.hidden_field :friend_id, value: friend.id
            = f.submit '新しいトークを始める'
- else
  友達はまだいません。
  = link_to '友人検索', search_friends_path , class: 'fa fa-cog'
  から友達を探してください。

app/views/friends/search.html.haml
.search_header
  = current_user.name
  = link_to '友人一覧', friends_path
  = link_to "ログアウト", destroy_user_session_path, method: :delete
.form
  = form_with model: Friend.new, class: 'search_form' do |f|
    = f.text_area :message, placeholder: '友達の名前を入力してください', class: 'input_message'
- @not_friends.each do |friend|
  .friends_index
    .friend_image
      = friend.name + "のアイコン"
    .friend_name
      = friend.name
    .start_talk
      = form_with model: Friend.new do |f|
        = f.hidden_field :friend_id, value: friend.id
        = f.submit '友達になる'